language: go
go:
  - 1.10.x
go_import_path: github.com/teamwork/validate
notifications:
  email: false
  webhooks: http://tw-bot.teamworkops.com:8182/travis/buildstatus
cache:
  directories:
    - $HOME/.cache/go-build
install:
  - ./bin/setup-travis
script:
  - cd $HOME/gopath/src/github.com/teamwork/validate
  - ./bin/test -race ./...
  - ./bin/coverage ./...
  - ./bin/lint ./...
