language: go
go:
  - 1.11.x
go_import_path: github.com/teamwork/validate
notifications:
  email: false
  webhooks: http://tw-bot.teamworkops.com:8182/travis/buildstatus
cache:
  directories:
    - $HOME/.cache/go-build
install:
  - ./bin/setup-travis
script:
  - cd $HOME/gopath/src/github.com/teamwork/validate
  - "[ -f go.sum ] && export GO111MODULE=on"
  - ./bin/coverage -race ./...
  - env GO111MODULE=off ./bin/lint ./...
